### ISSUE TITLE
Face to face meeting Princeton/Rutgers

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#102]

**Comment by mturilli** [comment]
March 5 or 6, whatever works best for the teams.

**Comment by mturilli** [comment]
Apologies, @andre-merzky will be at Rutgers 8-16 March. Could we have our meeting at Rutgers either 10, 12 or 13 of March?

**Comment by jeroentromp** [comment]
My preference would be March 10.

Jeroen

On Jan 26, 2020, at 6:15 PM, Matteo Turilli <notifications@github.com<mailto:notifications@github.com>> wrote:


Apologies, @andre-merzky<https://github.com/andre-merzky> will be at Rutgers 8-16 March. Could we have our meeting at Rutgers either 10, 12 or 13 of March?

**Comment by mturilli** [comment]
Confirm March 10 at Rutgers.

**Comment by mturilli** [comment]
After internal discussion, the Rutgers team will be happy to go to Princeton. See you soon there!

**Comment by mturilli** [comment]
Yes, we are indeed planning to be there at 10am. Should be there before then?

**Comment by jeroentromp** [comment]
10 am is fine, but earlier would mean we can probably finish by noon. You want to avoid rush hour, but 9:30 may be OK?

On Mar 4, 2020, at 4:02 PM, Matteo Turilli <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, we are indeed planning to be there at 10am. Should be there before then?

**Comment by mturilli** [comment]
We will aim for 9:30am then.

**Comment by wjlei1990** [comment]
Hi Matteo, do you have any plans for the meeing in your mind? Do we need to prepare anything for the meeting?

**Comment by mturilli** [comment]
Due to the covid-19 containment policies, this meeting will be now held remotely. Here a tentative agenda, please edit and add as you see fit: https://github.com/radical-collaboration/hpc-workflows/wiki/F2F-Meeting-09-Mar-2020-(PU,RU)

**Comment by wjlei1990** [comment]
Hi All, we have updated our slides in the wiki
