### ISSUE TITLE
mongodb URL issues

### ISSUE THREAD

**Issue by wjlei1990** [radical-collaboration/hpc-workflows#107]
Hi, 

Which mongodb url should we use for  Princeton team? Do we need to create our own?

In some old [docs](https://github.com/uvaaland/pugeo-userguides/blob/master/entk-on-princeton-desktop/00_installing_entk_on_princeton_desktop_computer.ipynb), it said we could use this one:
```
export RADICAL_PILOT_DBURL="mongodb://user:user123@ds043012.mlab.com:43012/princeton"
```

But I tried and it doesn't work any longer.

**Comment by mturilli** [comment]
Since when it was acquired by MongoDB, mlab API broke and we moved away from it. Please ping me on Slack and I will give you a usable mongodb server endpoint.

**Comment by wjlei1990** [comment]
Hi Matteo, I tried to log into the old workspace in slack but it seems somehow been de-activated. Could you send me another invitation link to your current workspace or so? My email account is: lei@princeton.edu

**Comment by mturilli** [comment]
Done, let me know whether the invitation works.
