### ISSUE TITLE
Test GPU support for RP on Titan

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#11]

**Comment by andre-merzky** [comment]
Is it possible to provide some GPU workload for testing?  It would be great to have some (lshort, informal) documentation on how to distinguish correct from incorrect execution (in the case where that is not obvious).  Thanks!

**Comment by vivek-bala** [comment]
#10 is now done.  The executable currently being used is cpu only, but there is also a gpu version. I will work on compiling that on Titan. Maybe we can work with that.

**Comment by mturilli** [comment]
Undergoing testing. Blocked by https://github.com/radical-cybertools/radical.pilot/issues/1441

**Comment by vivek-bala** [comment]
Hey @wjlei1990 
Wrf to the latest email exchanges, if you agree the output files are consistent with what you expected, please close this ticket.

**Comment by mpbl** [comment]
Forgot to close it before. It seems good.
