### ISSUE TITLE
GPUMPS support for PU workflows

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#113]

**Comment by andre-merzky** [comment]
Is this a duplicate of #100?  If not, then I am not sure I remember what this ticket is about, apologies - does anybody have more details, please?

**Comment by wjlei1990** [comment]
Seems a duplicate one. There are tickets open for both summit and tranverse cluster.

**Comment by mturilli** [comment]
Closed as a duplicate of #100
