### ISSUE TITLE
Can I control the job layout using ENTK?

### ISSUE THREAD

**Issue by wjlei1990** [radical-collaboration/hpc-workflows#121]
Can I control the job layout using ENTK?

For example, on summit each node has two POWER9 processors. If I have a single-thread task and I want to put two taks on one node so each POWER9 will get exactly 1, how can I do that?

**Comment by andre-merzky** [comment]
Alas you can't influence that on API level.  If this has a significant performance impact, we can change the agent scheduler to ensure socket locality for threads.  Can you measure what the impact is?

**Comment by wjlei1990** [comment]
I am just wondering :) I haven't done any performance metric yet. I don't think it will impact the performance that much.

**Comment by andre-merzky** [comment]
I don't think so either :-)  But let us know if you have indications otherwise, ok?

**Comment by wjlei1990** [comment]
Maybe I should ask in another way. Can I control how many tasks(single thread) to be put onto 1 node?  Some of my (single-threaded) tasks are IO and memory intensive. So I don't want all of them to squeeze on 1 node.

---
I guess the answer is also No, right?

**Comment by andre-merzky** [comment]
Ah, that's a fantastic use case: I also need that capability right now :-)

https://github.com/radical-cybertools/radical.pilot/issues/2139
