### ISSUE TITLE
Request MongoDB and RabbitMQ endpoints if needed

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#124]
All, please enter your request in this spreadsheet (you will have to request access):
https://docs.google.com/spreadsheets/d/1Z-UNb6U7x6KPZbsV7Zcey_Cgx_UuHR_Sj-FYzkONEiE/

**Comment by wjlei1990** [comment]
Princeton got the new MongoDB endpoints.

**Comment by Weiming-Hu** [comment]
Penn State requested access to the shared document.

**Comment by mturilli** [comment]
You should be able to access it now

**Comment by Weiming-Hu** [comment]
Will my credential appear later in the sheet? Sorry I'm not sure what I should do.

**Comment by mturilli** [comment]
Just fill in your request in the mongodb and rabbitmq tabs (down on the left) and we will create them for you. I will send you your password privately.

**Comment by Weiming-Hu** [comment]
I have put down my name only. Is there anything else I should do?
