### ISSUE TITLE
Supporting ORNL Andes

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#128]
https://www.olcf.ornl.gov/olcf-resources/compute-systems/andes/

**Comment by wjlei1990** [comment]
In `radial.saga`, the `self.rm.host()` returns `localhost`. So `saga` is not aware of the system.

After some modification on the source code, the `radical.saga` now works on andes.

Plan to move to `radical.pilot` and `radical.ensemble` soon.

**Comment by andre-merzky** [comment]
> After some modification on the source code, the `radical.saga` now works on andes.

What modifications are those?

**Comment by wjlei1990** [comment]
The code change I made are in the file of `adaptors/slurm/slurm_job.py`.

Since `self.rm.host` are `localhost`. So I manually set the value to `andes`:
```
self.rm.host = "andes"
```

There are a few changes to the header information.
```
if 'andes' in self.rm.host.lower(): 
    script += "#SBATCH --chdir %s\n"   % cwd    # instead of --workdir

if 'andes' in self.rm.host.lower(): 
    script += "#SBATCH -N %d\n" % n_nodes
```

**Comment by wjlei1990** [comment]
pull requests submitted https://github.com/radical-cybertools/radical.saga/pull/823
