### ISSUE TITLE
Deprecation message in EnTK

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#129]
See https://github.com/radical-cybertools/radical.entk/issues/523

**Comment by mturilli** [comment]
@lsawade please try the latest EnTK release 1.5.8. The deprecation message should now be printed only once. Feel free to consider updating your script to avoid the deprecation message and let us know whether you need help with that.

**Comment by lsawade** [comment]
Looks good! No more unnecessary prints after I fixed the deprecation messages. Thanks!
