### ISSUE TITLE
Add quick check that checks task requirements vs. workflow requested requirements?

### ISSUE THREAD

**Issue by lsawade** [radical-collaboration/hpc-workflows#139]
A simple check that goes through the task resource requirements, and then checks against the dictionary of the AppManager.

It has happened to me now a couple of times that I - by accident - asked for more resources in a task than I ask for in the app manager for test cases. This lead to hanging of the task. It could be that this is specific to `SLURM`.

This also leads to the `unit0000*/` directories not being created, and hence I can't check whether the submit scripts are ok.

I'm attaching the debug log, just in case.

#### Log
[radical.log](https://github.com/radical-collaboration/hpc-workflows/files/5945168/radical.log)

**Comment by andre-merzky** [comment]
Hi @lsawade - this related to [this issue](https://github.com/radical-cybertools/radical.pilot/issues/2129) in radical.pilot, and is not related to Slurm.  We have that issue at low priority at the moment, but given your ticket here we'll try to address it soon.  Thanks for letting us know!

**Comment by lsawade** [comment]
oh great and not great, I guess! I mean it's not that stuff isn't working, it's more a convenience feature.

**Comment by andre-merzky** [comment]
This has been resolved by RP release 1.6.7.  Thanks for your patience! :-)
