### ISSUE TITLE
SRS document for PSU use case

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#14]
Depends on #4

**Comment by mturilli** [comment]
Ongoing

**Comment by vivek-bala** [comment]
Iterated on the SRS for PSU. @Weiming-Hu @cervone can take a look at it now.

**Comment by vivek-bala** [comment]
SRS at https://docs.google.com/document/d/1VnitoSASx40SsTCIvx9Xav7MLR1gFqFrN3rogxRLaqQ/edit#

**Comment by Weiming-Hu** [comment]
Thank you!

Weiming

**Comment by mturilli** [comment]
Year 1 is done
