### ISSUE TITLE
Missing documentation for the -d option in radical-pilot-create-static-ve

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#145]
The current documentation has the following information:

```
(venv_Predictability) wuh20@cheyenne3:~> radical-pilot-create-static-ve

    ERROR: missing target

    usage: /glade/u/home/wuh20/venv_Predictability/bin/radical-pilot-create-static-ve -p <path> [-v <version>] [-t <type>] [-m <modules>]

    This script creates a virtualenv at the given target path.  That
    virtualenv should be suitable to be used as static VE for a radical.pilot
    target resource, and can be specified in a resource configuration for RP.

    type   :  *default*, bwpy (Blue Waters support)
    version:  python version to use
    modules:  comma separated list of modules to install
```

However, it misses the `-d` option which installs the default modules required. Honestly, I would prefer it to be the default behavior of the command because I don't really know what modules I need. The default modules always solve my problem.

My radical stack is as follows:

```
(venv_Predictability) wuh20@cheyenne3:~> radical-stack

  python               : /glade/u/home/wuh20/venv_Predictability/bin/python3
  pythonpath           :
  version              : 3.7.9
  virtualenv           : /glade/u/home/wuh20/venv_Predictability

  radical.analytics    : 1.6.7
  radical.entk         : 1.6.5
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.6
  radical.saga         : 1.6.6
  radical.utils        : 1.6.7
```

This issue has been raised in [this previous issue](https://github.com/radical-collaboration/hpc-workflows/issues/138#issuecomment-847922188) and my [instructional post for EnTK](https://weiming-hu.github.io/EnTK-Cheyenne-Setup/#setting-up).

**Comment by andre-merzky** [comment]
Thanks for the feedback! The documentation certainly needs to get fixed.   We'll discuss the default setting also.

**Comment by mturilli** [comment]
Will be in the next release
