### ISSUE TITLE
Possible to put a timeout in the jsrun command?

### ISSUE THREAD

**Issue by wjlei1990** [radical-collaboration/hpc-workflows#146]
Hi team,

Is it possible to put `timeout` in the `jsrun` command?

I used to run the command like this:
```
timeout 300 jsrun -n384 -a1 -c1 -g1 ./bin/xspecfem3D
```

**Comment by andre-merzky** [comment]
Hi @wjlei1990 - we don't support timeouts at the moment.  A quick workaround would be to wrap the task in a shell script and to kill it after some time.  Please let us know if you need help with setting this up!

**Comment by wjlei1990** [comment]
Hi @andre-merzky, could you be more specific?

So originally I have this:
```
timeout 300 jsrun -n384 -a1 -c1 -g1 ./bin/xspecfem3D
```

What should I put into the shell script, and how should I prepare the entk commands?

**Comment by andre-merzky** [comment]
Hi @wjlei1990, 

if `timeout` is available on the compute nodes, you could change the EnTK task description from
```py
executable = './bin/xspecfem3D'
arguments  = []
```
to
```py
executable = 'timeout'
arguments  = ['300', './bin/xspecfem3D']
```

If that is not an option, have a look at [this stackoverflow page](https://stackoverflow.com/questions/687948/timeout-a-command-in-bash-without-unnecessary-delay) for a couple of ways on how to time out a command.  Let me know if that helps!
