### ISSUE TITLE
any way to get radical job id

### ISSUE THREAD

**Issue by wjlei1990** [radical-collaboration/hpc-workflows#149]
Is there any way to get radical job id?

```
re.session.login4.lei.018849.0008
```

For example, I want to get the `018849.0008` when running python script. Any way to do it?

**Comment by wjlei1990** [comment]
Also, is there anyway to get slurm job id?

I usually have multiple jobs running. So having those job ids will make tracking progress much easier.

**Comment by andre-merzky** [comment]
The session ID should be returned by `AppManager.sid`:
```
$ python3
>>> import radical.entk as re
>>> amgr = re.AppManager()
>>> amgr.sid
're.session.rivendell.merzky.018859.0000'
```

> Also, is there anyway to get slurm job id

I am afraid that this is not exposed by the RE API :-/  But, you should be able to set a `job_name` in the resource description, and that job name is also set on the slurm job.  Slurm commands allow to look for job names also IIRC, or you can at least grep for it.
