### ISSUE TITLE
User level database

### ISSUE THREAD

**Issue by mpbl** [radical-collaboration/hpc-workflows#20]
I have tried to sketch what the requirements would be for a "user-level" database for our use case.
It's far from complete but I'd like some comments to see if it makes sense for the Radical team.

[Link to the google doc.](https://docs.google.com/document/d/1M9341Y6_9zmF0amUY9bafseyoCOmCehTHNIRpGwDc9o/edit#)

**Comment by mturilli** [comment]
Unfrozen.

Possibly related to #21
