### ISSUE TITLE
Generating visualization / feature extraction

### ISSUE THREAD

**Issue by mpbl** [radical-collaboration/hpc-workflows#21]
Right now just a reminder for later on.
We might want to add additional visualization layers, which will potentially generate hundreds (or more) images.

**Comment by mturilli** [comment]
Unfrozen.

Requirement elicitation:
* What kind of visualization/feature extraction do you need?
* At runtime or at the end of one simulation e/o analysis run?
* Other?

**Comment by mpbl** [comment]
Matthieu to open an mail thread to meet with Ebru
