### ISSUE TITLE
Get access and allocation on Yellowstone and upcoming Cheyenne 

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#22]
Provide link to form to create an account and get added to the allocation.

**Comment by mturilli** [comment]
Confirm whether Andre gained access (and Manuel int the medium term)

**Comment by andre-merzky** [comment]
Not to my knowledge...

**Comment by mturilli** [comment]
Andre to gain access while visiting Rutgers next week.
