### ISSUE TITLE
Move preprocessing section PU workflow to Rhea

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/hpc-workflows#27]
Currently blocked by the following tickets: #19 #17 and https://github.com/radical-cybertools/radical.pilot/issues/1187

**Comment by mturilli** [comment]
Support ready for testing as per https://github.com/radical-cybertools/radical.pilot/issues/1187#issuecomment-324745039

**Comment by vivek-bala** [comment]
Rhea support is now implemented. Currently, testing Rhea access from Titan.

**Comment by vivek-bala** [comment]
#19 is also resolved. 

https://github.com/radical-cybertools/radical.pilot/issues/1187 is reopened due to recent changes on Rhea.

**Comment by vivek-bala** [comment]
Blocked by https://github.com/radical-cybertools/radical.pilot/issues/1473

**Comment by mturilli** [comment]
Reha has been rebooted. Rutgers to check whether the issue has been addressed.

**Comment by mturilli** [comment]
Provided scripts to PU for testing. Ongoing.

**Comment by uvaaland** [comment]
Easiest would be to have everything run on Summit, but @jeroentromp said that they were not allowed to do the preprocessing on Titan and had to do it on Rhea. Therefore, this action is still relevant unless things have changed for Summit.
