### ISSUE TITLE
Identify Science Problem for PY1 Paper  (~01 October, 2017)

### ISSUE THREAD

**Issue by shantenujha** [radical-collaboration/hpc-workflows#3]
Consistent with our PY1 [objectives](https://docs.google.com/presentation/d/1QtEGwhFiA58Gr8IXenQ3CAo6gkluoHhp0N73Cunoc54/edit#slide=id.g1c1f3fb901_0_0), we want to produce a paper from the project by Oct 01, 2017.

This paper will identify a science problem (from each track) of interest and show how the CI (Cyberinfrastructure) has been used to achieve the science objectives. The focus is on the CI aspects and not on the science objectives per se. But the CI has to be well motivated by the science problem.

Ideally this paper will go to "Applications Track" of IPDPS'18 -- a top CS conference.

**Comment by shantenujha** [comment]
I propose to focus on this after April 17 submission of AHM abstract.

**Comment by mturilli** [comment]
Brief initial draft of the Science Problems (PR and PSU) due on Apr 19.
