### ISSUE TITLE
move all UC documents and SRS to hpc-workflows google drive?

### ISSUE THREAD

**Issue by shantenujha** [radical-collaboration/hpc-workflows#32]
To facilitate sharing, collaboration and reporting, we should probably move all SRS/UC documents to a folder under the main project google drive:

https://drive.google.com/drive/u/0/folders/0BxWZQExiTsWNV2dLSGZUeXFVRVU

**Comment by vivek-bala** [comment]
We have the UC, SRS and the IPDPS paper in the hpc-workflows in the google drive.
