### ISSUE TITLE
multiple events pilot / lustre compromise

### ISSUE THREAD

**Issue by mpbl** [radical-collaboration/hpc-workflows#34]
Adapt Vivek entk scripts to generate 'tasks' composed of a limited number of earthquakes.

**Comment by mpbl** [comment]
Lustre friendly, Pilot unfriendly: 40 simultaneous runs
Lustre unfriendly, pilot friendly: 1 simultaneous run

Compromise: 5 to 10 simultaneous runs

**Comment by vivek-bala** [comment]
VB: Currently translating changes in RP (for GPU) to EnTK. I will use the data available in https://github.com/radical-collaboration/hpc-workflows/tree/master/scripts/regional_Greece_small/forward_simulations to run with the GPU as well.

**Comment by mturilli** [comment]
To be measured via IPDPS experiments

**Comment by mturilli** [comment]
Mitigated and possibly addressed by the capabilities offered by EnTK. We will revised it if needed once in production.
