### ISSUE TITLE
Specify pseudoplots for PU experiments, IPDPS paper, subsection 5.4.2

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#35]

**Comment by vivek-bala** [comment]
One idea could be to run 40 simulation tasks (each using 384 GPUs) and run X simulation tasks (each using Y CPUs). This way we are not wasting the CPUs on these 16K nodes and getting more concurrent simulations. We can determine X and Y based on the distribution of the execution time  of the forward simulations on the CPUs and GPUs.

**Comment by mturilli** [comment]
Ongoing

**Comment by vivek-bala** [comment]
We have a table for this in the paper. Closing
