### ISSUE TITLE
Does ENTK work with XSEDE Single Sign on Login Hub method

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#37]
Let me clarify what I mean by that.

XSEDE recommends one uses the XSEDE Single Sign on Login Hub to login to XSEDE resources with the local username and password. This is very helpful when I have an account with no specific username and password for every supercomputers. Does ENTK work in this type of setting? I remember that I need to set up passwordless ssh to supercomputers. But in this case, will it work if I can successfully gsissh to supercomputers through XSEDE Login Hub?

Thank you

**Comment by vivek-bala** [comment]
Not really, you will have to setup the passwordless ssh access directly to the machine you wish to use.

**Comment by vivek-bala** [comment]
The commands for setting up gsissh access on ubuntu/mac can be found here: https://github.com/vivek-bala/docs/tree/master/misc

Remember to obtain the certificate every ~12-24 hrs using the ```myproxy-logon -s myproxy.xsede.org -l <username>``` command. Once you do that, you can then use the ```gsissh -p 2222 stampede.tacc.xsede.org``` command (or similar for other systems).

**Comment by Weiming-Hu** [comment]
Thank you. This is done.
