### ISSUE TITLE
Improve error messages across RCT

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#38]
Please collect here notes/comments/suggestions

**Comment by Weiming-Hu** [comment]
needs more guidance on how to locate the error log files, and make sense of the error messages to users. This could potentially help them submitting more specific tickets and getting direct help to solving the question.

**Comment by Weiming-Hu** [comment]
consideration between shooting out an error or providing a suggestion. This arms the interface of EnTK with a sense of intelligence that it guesses what the users are trying to do and what they are missing.

**Comment by mturilli** [comment]
Ongoing, @Weiming-Hu and @vivek-bala to sync and decide what messages should be implemented.

**Comment by mturilli** [comment]
* Improve reporter logger with shorter and better messages.
* Improve documentation with information on how to manage those errors.

**Comment by vivek-bala** [comment]
Created a ticket https://github.com/radical-cybertools/radical.entk/issues/206. This issue will be addressed in the next EnTK release (week of Feb 19) and can be skipped till then.

**Comment by mturilli** [comment]
Reporter to be included in the next point release (0.6.2).

**Comment by vivek-bala** [comment]
WH to investigate the new released version (0.7.*) and comment.

**Comment by Weiming-Hu** [comment]
This issue will be tested using the latest version of AnEn once the development is complete.
