### ISSUE TITLE
Skewed performance by fileIO

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#39]
From the initial experiments, it turns out that most of the application time is consumed by the fileIO process, which reaches about 90%. Although relatively fewer stations and test days are computed, which might conceptually amplify the difference between the computing time and fileIO time, we need to discuss and come up with some possible solutions for a faster fileIO.

**Comment by Weiming-Hu** [comment]
@mturilli has proposed using a RAM disk, and to start another task, before the actual AnEn calculation, to read the data into RAM in advance. [forgive my unprofessional descriptions...]

**Comment by Weiming-Hu** [comment]
Wait until the complete script is done. And we will decide on the parallel scheme based on the actual time required by the execution.

**Comment by mturilli** [comment]
Ongoing. To be measured by IPDPS experiments

**Comment by Weiming-Hu** [comment]
At current stage, AnEn is data intensive, and thus it just takes time to read and write data. Close it for now.
