### ISSUE TITLE
Coordinate with workflows and data-intensive computing group at OLCF for PU activity

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#45]
Identify requests to make to ORNL to support use case

**Comment by shantenujha** [comment]
468E9BB0-585E-4CC6-A749-E9C14C4DA6CE

**Comment by mturilli** [comment]
Ping end of January

**Comment by mturilli** [comment]
Shantenu to ping them

**Comment by shantenujha** [comment]
Pinged ORNL team on 2/04.

**Comment by mturilli** [comment]
No answer from the group. Parked until they resurface.
