### ISSUE TITLE
Attempt production run of PU use case

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#46]

**Comment by mpbl** [comment]
blocked (kind of) by #47

**Comment by mpbl** [comment]
Hi, Vivek,

when trying to run on Titan, I have got the following error:

```
NoSuccess: Could not detect shell prompt (timeout) (/ccs/home/mpbl/miniconda2/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
```

the full log is [there](https://gist.github.com/mpbl/819170b70ad8186297dc410ef1ff25c3)

Chances are that I am not defining the entk/pilot resource properly. Would you mind taking a look at the [config file](https://bitbucket.org/mpbl/simpy/src/b44523d92aa8b9e489f6206b7580b1103ca42e43/entk_config_files/entk_config_ornl.yml?at=entk_integration&fileviewer=file-view-default) and tell me if something looks wrong to you.

Thanks.

**Comment by vivek-bala** [comment]
Hey Matthieu, can you try again after setting the following: ```export SAGA_PTY_SSH_TIMEOUT=300```. 

Also, I noticed that the path to EnTK and RP files are different:
```/autofs/nccs-svm1_home1/mpbl/radical.entk/src/radical/entk/appman/appmanager.py```
```/ccs/home/mpbl/miniconda2/lib/python2.7/site-packages/radical/pilot/compute_pilot.py```

Is that expected? Generally both EnTK and RP are installed in the same virtualenv (or conda env).

**Comment by mpbl** [comment]
I believe the paths are different because rp was installed with ```pip install .``` and entk with ```pip install -e .```

Let me check how it goes with your suggested environment variable.

**Comment by mpbl** [comment]
Hi, Vivek,

Thanks, it helped.
I have then got another problem, I believe all processes are running on the same node due to the following command getting issued:
```
/sw/xk6/xalt/0.7.5/bin/aprun -L 509 -n 6 ./bin/xspecfem3D
```
I know you solved this issue a while ago in RP. I am using the RP's latest master branch. Is it the one I should use?

**Comment by mpbl** [comment]
Update: it works fine, for a smaller test case on Titan.

@vivek-bala 
There is one thing I find confusing:
```
      cpus: 400 # width of the pilot job
      gpus: 25 # width of the pilot job
```

I originally set cpus to be equal to gpus, a on Titan one node has a single cpu and a single gpu.
However, this ```cpus``` variable seems to be passed to rp's ```cores``` variable (this is confirmed by looking at what is reversed by the scheduler).

**Comment by mturilli** [comment]
Ongoing, ready to test at higher scale
