### ISSUE TITLE
Porting EnTK to Summit

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#48]

**Comment by mpbl** [comment]
Started the process to adding Rutger's team to summit-dev.

**Comment by mturilli** [comment]
Manuel, Vivek, Matteo, Shantenu to gain access

**Comment by shantenujha** [comment]
Manuel, Vivek, Matteo have confirmed access.

**Comment by vivek-bala** [comment]
Documentation about jsrun on Summit: https://www.olcf.ornl.gov/for-users/system-user-guides/summit/running-jobs/#job-launcher-jsrun

**Comment by vivek-bala** [comment]
Better to focus directly on Summit. Changing title of ticket.

**Comment by vivek-bala** [comment]
https://github.com/radical-cybertools/radical.pilot/issues/1616

**Comment by vivek-bala** [comment]
https://github.com/radical-cybertools/radical.pilot/issues/1574

**Comment by mturilli** [comment]
First milestone reached: end-to-end executions of single and multi-node, not-MPI and MPI compute units on SummitDev. Summit is still unavailable due to acceptance test.

**Comment by mturilli** [comment]
Ported.
