### ISSUE TITLE
Tutorial about EnTK/RCT at SEA conference: Apr 5, 2018

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#50]
* SEA, Boulder Colorado, April 4.
* 1/2 or 1 day tutorial? Make this decision by Feb 7. Depends on #28 
* Target audience?

**Comment by Weiming-Hu** [comment]
https://sea.ucar.edu/conference/2018

**Comment by shantenujha** [comment]
@vivek-bala @mturilli  -- What is the result of the initial assessment? As per ticket, we needed to converge on SEA (or not) by yesterday.

**Comment by vivek-bala** [comment]
Confirmed: No system limitation on number of concurrent mpirun or mpiexec_mpt jobs

**Comment by mturilli** [comment]
@vivek-bala I would suggest the following roadmap for supporting Cheyenne:
1. Enable job submission via Saga (it may be ready or require some modification to the current connector)
2. Bootstrap one pilot on a single node (no MPI required)
3. Bootstrap one pilot on multiple nodes once RP#1552 is addressed.

Does this look reasonable?

**Comment by vivek-bala** [comment]
Yes, I agree with the order. 1 and 3 can definitely be done concurrently. 

For 2, I will need to first test if I can submit a job with no launch method. If not, 2 depends on 3.

**Comment by vivek-bala** [comment]
1. Pending: https://github.com/radical-cybertools/saga-python/issues/657
2. A job can be started with no launch method. Submitted a pbs script with a simple /bin/date executable and no launch cmd (mpirun, mpiexec)

**Comment by vivek-bala** [comment]
The SAGA issue has been fixed. Currently blocked by https://github.com/radical-cybertools/radical.pilot/issues/1551

**Comment by shantenujha** [comment]
@vivek-bala @mturilli Is it fair to assume that we will not be making plans for a hands-on tutorial at SEA? I think we need to get back to Guido ASAP so he can confirm whether to ask for a full-day or half-day tutorial, which in turn depends upon us.

**Comment by mturilli** [comment]
This depends on the estimated ETA for supporting Cheyenne. If the decision needs to be made now, then I would opt for not committing to it as we would risk not to be able to deliver **if** some major issue surfaces with supporting Cheyenne.

**Comment by Weiming-Hu** [comment]
We had a meeting discussing about the plan for SEA workshop. Since Cheyenne wouldn't be ready, we decided to limit the problem scale so that a regular laptop can handle the computation.
