### ISSUE TITLE
Agenda for RU visit at PSU: May 8, 2018

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#52]
March 2018, week 2-4?

**Comment by shantenujha** [comment]
Tentatively scheduled for March 16 (day long). Rutgers team arrive the evening before.

**Comment by Weiming-Hu** [comment]
The date of Rutgers' visit is set on Tue, May 8th.

**Comment by mturilli** [comment]
To agree upon an agenda for the visit.

**Comment by Weiming-Hu** [comment]
Tentative agenda
https://docs.google.com/document/d/1se0szbXzH0xKJTBTa4QAY1Y61dqo37Aqj5mnHHq4Yqo/edit?usp=sharing

**Comment by Weiming-Hu** [comment]
Closing this ticket after the meeting.
