### ISSUE TITLE
Upload document PU use case Y2 to google drive

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#53]

**Comment by vivek-bala** [comment]
Link to the document: https://docs.google.com/document/d/1SnJ2soxARSgHd8w3HYbHrj6-gBcIeJgzUvVWSYVvZwI/edit#

**Comment by mpbl** [comment]
Use case does not change for Y1. 
Added a few things to indicate where requirements differ slightly in case we would like to run on a newer system.

**Comment by mturilli** [comment]
Change the tile (iteration) and then close the ticket
