### ISSUE TITLE
Large Scale Test on SPECFEM3D Globe

### ISSUE THREAD

**Issue by wjlei1990** [radical-collaboration/hpc-workflows#54]
We recently did a large scale simulation test using `entk`, `simpy` and `SPECFEM3D GLOBE`.

The sandbox is at: `/lustre/atlas/scratch/lei/csc143/radical.pilot.sandbox/rp.session.titan-ext4.lei.017574.0000`.

The job contains 40 independent simulations, each using 384 GPUs(nodes). In total, it uses about 15,400 nodes on Titan@ORNL.

Based on our test, we found the timeline:

| Time           |  Task                 |
| ------------- |:-------------:|
| 5 mins            | Radical Setup |
| 5 mins            | Run the Mesher |
| 5 mins            | Copy the mesh(from sandbox to stage dir) |
| Remaining time | Run the Solver |

Also, we found between each solver runs, there is about 30 sec lag, which I think it is for RADICAL to set things up for each individual simulations. Given we are running 40 simulations at the same time, the lag between first run and the last run(40th run) would be ~20 minute, which we think it is kind of *significant* overhead.

PS: the `copy the mesh` took about 5 mins, which we think is also bit long, cause the files are copied from "/lustre/atlas/scratch/lei/csc143/radical.pilot.sandbox/rp.session.titan-ext4.lei.017574.0000/" to "/lustre/atlas/proj-shared/geo111/Wenjie/entk/stage_out_mesher". How do we modify the directory of `sandbox`, to make them on the same disk and speed up the copy operation. @vivek-bala

**Comment by andre-merzky** [comment]
Hey - I have a couple of questions on the run:

  * I am afraid I can't access that pilot sandbox - could you either open it up (and all parent dirs) or attach a tarball to this ticket?  
  * In case you did not do so already, can you rerun with `export RADICAL_PILOT_PROFILE=TRUE` in your environment?  This will enable more fine grained bookkeeping about the RCT stack's performance.
  * would you be able to link input data instead of copying them?  @vivek-bala may be to answer this one...

Thanks, Andre

**Comment by vivek-bala** [comment]
Hey Andre, I am going to meeting with Wenjie/Matthieu to take a look at the profiles. Linking might work but the delay seems to come from the src and tgt being in different file systems. We might try out both linking as well as moving the sandbox to where the raw data is.

**Comment by andre-merzky** [comment]
I am not sure why a different file system would mean a slower file system - is that really the case?  Linking across different FS should be (almost) as fast as linking on the same FS.

**Comment by vivek-bala** [comment]
I am not sure if linking is slow. I meant we will try that out as well :) But it seems like copy is considerable slow across different FS.

**Comment by andre-merzky** [comment]
We may be saying the same then - linking should avoid the copy...

**Comment by mpbl** [comment]
Hi, Andre:
About the copy: at the end of the meshing, we try to ```mv``` the data to some other directory. The idea is to allow simulations to run from a pre-computed mesh. We could link the data there instead of trying to move them.

The intuition was that the move was slow because the data are moved from atlas1 to atlas2 (or conversely) and that staying on a single FS might help avoiding this spurious copy. But it might not be the case.

I am not a big fan of linking, because in case several pilots are required, data from the first pilot would be accessed by the subsequent pilots. IMO, it breaks the self-contained property inherent to pilots.

Thanks, Matthieu

**Comment by vivek-bala** [comment]
@andre-merzky I don't think there is a method to link the output in EnTK. I think that might help here. IIRC there was some issue when I created a directive for it in RP, but let me try it out again.

**Comment by mpbl** [comment]
Just fyi, the ```mv``` is something we specify in the post_exec script. If it's slow it is on us.

**Comment by vivek-bala** [comment]
Maybe, I am not sure. I had a chat with Wenjie and mentioned some environment variables that will give us more detailed profiles. We can analyze those to nail down on the reason.

Also, thanks Matthieu. It might be a good idea to include properties in EnTK to move input and output data as well!

**Comment by andre-merzky** [comment]
@mpbl : about that self-containment: that is not something RP really enforces.  We recently introduced some shared staging space to specifically support use cases where data are to be shared between different pilot spaces.  I am not sure if entk can use that already thoug;h...

**Comment by wjlei1990** [comment]
@vivek-bala : I just did a performance test on Titan using 4 concurrent SPECFEM forward runs.  We may check sometime together. There is a few issues I encountered in the runs:

1) the pilot didn't get terminated after the simulation finished. There is some message keep repeating on the terminal:
  ```
  018-02-20 15:37:14,516: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Sent heartbeat response
  ```
2) `simpy` didn't move the `synthetic.h5` to solver stage out directory.

**Comment by vivek-bala** [comment]
Hey Wenjie, 1 is resolved in the master. If you are using the gpu branch, I can merge the fix to that branch as well. I would need to see the logs to debug 2.

Most times tomorrow work for me (except 2.30-3pm). Let me know when we can take a look.

**Comment by wjlei1990** [comment]
Hi Vivek, could you do the merge so I can resubmit my test and see if it works. Let me know when you are done with the merge.

I am available most time of this week. (but not today since I left my laptop at home)

**Comment by vivek-bala** [comment]
Sure, let me get to that this evening. I will have it merged and ready so that you can use it tomorrow.

**Comment by vivek-bala** [comment]
Hey Wenjie, the gpu branch should be ready to test again. Just to be sure, please use the following stack:
```
radical.entk         : feature-gpu
radical.pilot        : feature-gpu
radical.utils        : devel
saga                 : feature-gpu
```

Let me know when you are available. Anytime other than 2-4pm E works for me. We can chat on slack to converge on a time.

**Comment by wjlei1990** [comment]
Hi Vivek,

I got errors when running jobs:
```
2018-03-12 15:02:03,500: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-03-12 15:02:03,501: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread: 
Traceback (most recent call last):
  File "/ccs/home/lei/miniconda2/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 423, in _enqueue
    self._mq_connection.close()
  File "/ccs/home/lei/miniconda2/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 688, in close
    self._flush_output(self._closed_result.is_ready)
  File "/ccs/home/lei/miniconda2/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 440, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/ccs/home/lei/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/ccs/home/lei/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/ccs/home/lei/miniconda2/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 441, in _enqueue
    raise Error(text=ex)
Error: Error: 

2018-03-12 15:02:03,505: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
```

Any ideas?

**Comment by vivek-bala** [comment]
Hey Wenjie, that error should be during termination. It is not a critical error and can be ignored.

**Comment by wjlei1990** [comment]
Maybe I am pointing to the wrong position of the log file.

Actually none of the jobs runs, not even the "unit.000*" is created. Give me some time to check from my side.

**Comment by wjlei1990** [comment]
My bad...The code actually runs but due to some module changes, I need to resubmit the jobs

**Comment by wjlei1990** [comment]
Hi Vivek, I got the new job finished. Maybe we can take a look at them together tomorrow.

Let me know what time works for you.

**Comment by mturilli** [comment]
Use the profiles for the meeting about analytics #56

**Comment by mturilli** [comment]
duplicate
