### ISSUE TITLE
Add integration tests specific to PSU and PU use cases as part of the tests pre-release

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/hpc-workflows#58]
Automate the integration tests as part of the pre-release testing

**Comment by mturilli** [comment]
Partially done, open and ongoing

**Comment by mturilli** [comment]
Done for PU, PSU ongoing. Tests will be triggered manually for auth issues.

**Comment by mturilli** [comment]
PSU ongoing.

**Comment by Weiming-Hu** [comment]
@vivek-bala I'm trying to set up passwordless access to Cheyenne. However, Cheyenne requires a token. I've tried the public rsa key but it looks like this does not work. Is there an alternative? Thank you.

**Comment by cervone** [comment]
I think the token is what you get from the ybkey.    There is a solution where you open a SSH tunnel, but you still need to enter the token at the beginning of the session



On Sep 24, 2018, at 2:58 PM, Weiming <notifications@github.com<mailto:notifications@github.com>> wrote:


@vivek-bala<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvivek-bala&data=02%7C01%7Cguc18%40psu.edu%7C24a7bc741c094caae6ff08d6224fac80%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636734122922148998&sdata=CjAGiRa992IGDH0A25%2B%2Bie7eA0V3cFwWRz4Udr%2BmJ7E%3D&reserved=0> I'm trying to set up passwordless access to Cheyenne. However, Cheyenne requires a token. I've tried the public rsa key but it looks like this does not work. Is there an alternative? Thank you.

**Comment by Weiming-Hu** [comment]
@cervone I can log onto Cheyenne without a problem. But to use EnTK I need to set up passwordless access. That's what stoped me.

**Comment by vivek-bala** [comment]
On Cheyenne, you can use the login node as the client (in place of your laptop). The changes in process limits were to accommodate this execution mode. Let me know how it goes.

**Comment by Weiming-Hu** [comment]
@vivek-bala Thank you. Working on this today. So I guess I need  to install radical.entk on Cheyenne log in node. Do I need rabbitMQ and MongoDB?

**Comment by vivek-bala** [comment]
Dependent on #65
