### ISSUE TITLE
Organize F2F meeting with PSU

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#60]
Oct-Nov timeframe, 2 days.

**Comment by mturilli** [comment]
* Proposing for PSU to visit Rutgers.

**Comment by mturilli** [comment]
26 should be fine, start to define the agenda. It would be desirable to close #65 but it will not be a deal breaker.

**Comment by Weiming-Hu** [comment]
Proposed [agenda](https://docs.google.com/document/d/1roJlvnUH1q-fO5TtInwQgMwhhr7020IGUbbIEF-6zS8/edit?usp=sharing)
