### ISSUE TITLE
Use case description for PU simulations on Summit

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#61]

**Comment by mturilli** [comment]
Create template document for this use case and share link here.

**Comment by mturilli** [comment]
This is a copy of the Y1 document. We can use it as a base to describe the changes required by Summit:  https://docs.google.com/document/d/1uugJsRRSTHDhMFb3NWaRRPwyoMiNPKn6sr2iO3IqMaQ/edit#

**Comment by wjlei1990** [comment]
There are a few things we planned to do on Summit.

1) Increase the number of earthquakes. Currently, we have 1,840 earthquakes that are ready to be used . We are thinking about expanding the data to 4,000 or 6,000 in the future. The computational cost goes linearly with the number of earthquakes, if using the same simulation resolution.

2) Bring in more model parameters. Our parametrization is based upon elastic model with transversely isotropic assumption. We are planning to bring in Q inversion, which will turn the model into anelastic one. The computational cost will increase by ~60% if using the same resolution.

3) Increase the resolution. Our model resolution is 17 sec and on summit we are planning to push it to 9 sec. This will the most challenging part of our study. Double the resolution usually result in 10 times increase in computation time and storage.

**Comment by uvaaland** [comment]
The above bullets are accurate. In terms of priority, @jeroentromp says that it is 1, 3 and then 2. First increasing the number of events, then pushing the resolution to 9 sec, then considering additional model parameters.
