### ISSUE TITLE
Performance characterization of PSU new implementation

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#63]

**Comment by Weiming-Hu** [comment]
A summary of reasons for program refactoring:

- Scientific reason: Separating similarity computation and the analog selection makes the program more flexible in providing detailed information, for example, the similarity metric, the mapping mechanism from forecast time to observation time. This change might lead to a larger memory requirement.
- Performance reseason: Redesigning several costly loops by using lookup tables and removing branching leads to a significant reduction (60%) in execution time. 
- Coding style: Refactoring also focuses on producing readable codes with a consistent coding style. Modulization and encapsulation help the program to be more extensible.

**Comment by Weiming-Hu** [comment]
Ongoing work: implementing python scripts and C++ executables on Cheyenne to lay the ground for coming experiments.

**Comment by mturilli** [comment]
Ongoing.

**Comment by Weiming-Hu** [comment]
https://github.com/radical-collaboration/hpc-workflows/blob/master/scripts/application_AnEn/year_2/profiling/profile.pdf

**Comment by vivek-bala** [comment]
Simulation kernel is profiled above. 

TODO:
* Update [wiki](https://github.com/radical-collaboration/hpc-workflows/wiki/Y2-Roadmap-PSU-Use-case) with profiles and experiment setup
* Experiments to be done with varying search space (currently fixed to 31 days)
* Use case document to be updated with details of the simulation kernel and how data is moved from
anen kernels to the simulation kernel

**Comment by mturilli** [comment]
Duplicate #67
