### ISSUE TITLE
PSU and PU science goals in year 2

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#68]
The PI should review the science goals achieved and about to be achieved in year 2 of the project. This will offer the base to define the requirements for the cyberinfrastructure in year 3.

**Comment by vivek-bala** [comment]
Roadmap added in a wiki at https://github.com/radical-collaboration/hpc-workflows/wiki/Y2-Roadmap-PSU-Use-case

**Comment by mturilli** [comment]
Agenda for #72

**Comment by mturilli** [comment]
Discuss with Jeroen and report back next meeting.
