### ISSUE TITLE
PSU and Rutgers F2F meeting at Baltimore

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#72]
Location: [Gordon Plaza](https://www.google.com/maps/place/Gordon+Plaza/@39.3036513,-76.614442,16z/data=!4m5!3m4!1s0x0:0x391a0830a75362fa!8m2!3d39.3058211!4d-76.6171677)

Date: Sunday, Dec 9

Time: 12:30 PM - 3:30 PM (tentative)

**Comment by vivek-bala** [comment]
WH, VB to create agenda for meeting

**Comment by vivek-bala** [comment]
Hi all, please find a draft of the meeting agenda at https://github.com/radical-collaboration/hpc-workflows/wiki/F2F-Meeting-09-Dec-2018-%28PSU%2CRU%29. Please feel free to add or edit any points to the agenda.
