### ISSUE TITLE
Create experiment to profile the execution of similarity_calculator and analog_selector

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/hpc-workflows#73]
Identified at least three parameters of the executables across which we want to profile the execution time and memory consumption.

Parameters: subgrid_size(SG), number of threads (NT), search space (SS)
T_simcalc = f(SG, NT, SS)
M_simcalc = g(SG, NT, SS)
T_anasel = h(SG, NT, SS)
M_anasel = j(SG, NT, SS)

Find f, g, h, and j when the executables are run on Cheyenne.

There may be more parameters than these three, please feel free to include them as well.

**Comment by vivek-bala** [comment]
Some plot ideas from F2F meeting:

![img_20181209_153303](https://user-images.githubusercontent.com/5543518/50240505-9c0d5380-038a-11e9-97b6-3d9d715707a4.jpg)

**Comment by vivek-bala** [comment]
Profiling to be done with the EnTK script developed in #77

**Comment by mturilli** [comment]
Profiled single-node. To be extended to multi-node.

**Comment by mturilli** [comment]
Blocked by uploading dataset to Cheyenne.

**Comment by mturilli** [comment]
Block by #83

**Comment by mturilli** [comment]
Ready to go for the first two stages.

**Comment by Weiming-Hu** [comment]
The paper on [PAnEn](https://weiming-hu.github.io/AnalogsEnsemble/) implementation and profiling has been submitted to the Journal of Earth Science Informatics. This paper covers profiling of the algorithm on a single node. Next step is to test AnEn with EnTK. But before that, I need make sure that the environment is properly set up (issue #88 and #87 ).
