### ISSUE TITLE
To discuss how Michael's phase of the workflow is derived from the current workflow

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/hpc-workflows#74]
Current understanding is that we run the current workflow (that exists for one test day) concurrently for multiple workflows.

**Comment by vivek-bala** [comment]
To be confirmed by PSU

**Comment by mturilli** [comment]
Ongoing. @Weiming-Hu to meet F2F with Michael and confirm.

**Comment by Weiming-Hu** [comment]
Scheduled meeting on Friday, Feb 1st.

**Comment by mturilli** [comment]
Ongoing.

**Comment by Weiming-Hu** [comment]
Implementing the minimal workflow and script with CMIP 5/6, AnEn, EnTK, and SolarSim.

**Comment by mturilli** [comment]
Ongoing

**Comment by Weiming-Hu** [comment]
Currently working on the paper on using AnEn for PV forecasts. Part of the work includes feeding the AnEn forecasts into SolarSim and see how this result compares with a neural network. The comparison will be helpful when we decide to run the simulation at larger scales.

**Comment by mturilli** [comment]
Weiming to execute two workflows that build upon each other. Likely, these workflows will not require new capabilities in EnTK
