### ISSUE TITLE
Document figure with entire workflow

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/hpc-workflows#75]
Create a neat figure of the workflow diagram from the F2F meeting

@mturilli to add picture of workflow
@vivek-bala and @Weiming-Hu to create a google drawing of the picture

**Comment by mturilli** [comment]
Here the picture:
![img_5552](https://user-images.githubusercontent.com/2323492/50242321-422c7e00-03ca-11e9-9e3f-b16313129be8.jpg)

**Comment by mturilli** [comment]
Iterate on the current drawing. Add link to the ticket.

**Comment by mturilli** [comment]
Ongoing. @vivek-bala to refine the figure.

**Comment by vivek-bala** [comment]
Figure: https://docs.google.com/drawings/d/1C2pZG4nkC4BGZ46efMhAZW_X37wO75ELWPLeRuzKbQk/edit?usp=sharing

Hey @Weiming-Hu take a look at this. If you agree, then I can move it into the google doc. Feel free to directly edit the figure.

**Comment by Weiming-Hu** [comment]
Hi Vivek. This looks good. Please add it to the doc. Thanks.

**Comment by vivek-bala** [comment]
Done. This ticket can be closed.
