### ISSUE TITLE
EnTK script for Year 2 PSU usecase

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/hpc-workflows#77]
I have added an initial script at https://github.com/radical-collaboration/hpc-workflows/blob/master/scripts/application_AnEn/year_2/entk_scripts. We have two configuration files: one for resource related parameters, other for workflow related parameters.

@Weiming-Hu and @vivek-bala to work for fill up remaining parts of the config file and entk script. Test on Cheyenne.

**Comment by mturilli** [comment]
@Weiming-Hu to try this on Cheyenne after populating the yml. Note: currently there are only placeholders for data movement. In case it is needed, the script will have to be amended.

**Comment by Weiming-Hu** [comment]
[Renewable simulator](https://github.com/Weiming-Hu/RenewableSimulator) is complete.

**Comment by Weiming-Hu** [comment]
EnTK + AnEn py script is complete. It is successfully run on local machine Sapphire.

**Comment by Weiming-Hu** [comment]
Set up personal local endpoint using personal globus connect. Uploading observations (1.9T) at a speed of ~80 MB/s.

**Comment by Weiming-Hu** [comment]
Data uploaded to Cheyenne.
