### ISSUE TITLE
F2F meeting Princeton/Rutgers

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#84]

**Comment by mturilli** [comment]
Realistically end of March, after Wenjie defended.

**Comment by uvaaland** [comment]
We are currently looking at at least two other use cases for EnTK in the group. These are projects that have some similar features to the global project but are different.

Jeroen has therefore aired the idea of having two F2F meetings. One being about the global inversion project once Wenjie is back, the other one being about these other use cases. Everyone is here that needs to be here for this other meeting, so we could potentially schedule it to take place sometime this month.

The idea would be for us to put together some material to explain to you what these other use cases involve, and then you could ask questions and help guide us on how to best design and codify the workflows.

Let us know your thoughts on this.

**Comment by mturilli** [comment]
Would 4/22 or 4/23 work for Princeton? Unfortunately, after that our calendars are very busy and it is difficult to find a day free for all until the second week of May.

**Comment by uvaaland** [comment]
Hi, Matteo! Tuesday 4/23 in the morning (before noon) is good for us.

**Comment by mturilli** [comment]
Discuss this again mid June

**Comment by mturilli** [comment]
10/11/19 planned

**Comment by lsawade** [comment]
Hi @mturilli, I won't be able to attend that week, because I am in Portland for a deep earth workshop. Is it possible to move the meeting up one week?

**Comment by mturilli** [comment]
Confirmed for 10/10, 10am

**Comment by jeroentromp** [comment]
Friday October 11, not 10/10.

On Oct 2, 2019, at 3:11 PM, Matteo Turilli <notifications@github.com<mailto:notifications@github.com>> wrote:


Confirmed for 10/10, 10am
