### ISSUE TITLE
Job efficiency on Cheyenne

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#87]
Hi, I have a question about how EnTK is managing tasks.

For a specific job submission below where I requested for 3600 cores (100 nodes) for 120 minutes in the resource script, I have the following record in Cheyenne allocation monitoring system:

Username | Job Id | Job Name | Queue Name | Submit Time | Start Time | End Time | # Nodes | Adjusted Core Hours
-- | -- | -- | -- | -- | -- | -- | -- | --
wuh20 | 4844372 | pilot.0000 | regular | 2019-03-29 09:11:54 | 2019-03-29 09:12:16 | 2019-03-29 09:39:04 | 100 | 1,608.00

Does the allocation start counting as soon as I start EnTK?

The reason why asking this is that actually for this specific job, my program hasn't started yet because of a configuration error which showed up later the process. It shows that the job ran for about 20 minutes, which I remember (if I'm not mistaken) this time was spent by EnTK submitting and transitioning tasks. Because there are about 400 tasks in a stage and EnTK seems to process them one by one and therefore it seems to take some time (20 minutes).

During these 20 minutes, were all 3600 cores just waiting? Because it looks like it from the figures ( 09:39 - 09:12 =  27 minutes; 27/60 * 100 = 1620 ~ 1608).

This specific job caught my attention because the sys admin reach out to me and notified me the inefficient job run. Below is the info I received:

JobID | UserName | Job Start_Time | Job_End_Time  |  #Nod  | #CPU | #CPU-hr  | #Wall-hr  | #Node-hr | %Eff
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
4844372 | wuh20   |   19/03/29 09:12:16  | 19/03/29 09:39:04  |  100  |   3600   |     0.00   |    0.45  |     44.67  |   0.0%

Thank you very much!

**Comment by andre-merzky** [comment]
AFAICS, this is indeed how EnTK is supposed to function: the resources are requested immediately.

> It shows that the job ran for about 20 minutes, which I remember (if I'm not mistaken) this time was spent by EnTK submitting and transitioning tasks.

What exactly was EnTK doing in that time, do you know?

**Comment by Weiming-Hu** [comment]
I don't know what EnTK is doing exactly. But based on my recollection, it is manging tasks from 0 - 599, like submission and transition.

**Comment by andre-merzky** [comment]
Can you please provide the log files?

@vivek-bala : Do you have any idea what EnTK could spend 20 min on?

**Comment by Weiming-Hu** [comment]
I don't have it saved. I need to resubmit jobs. Let me update this when I get the log files. Thank you.

**Comment by andre-merzky** [comment]
Thank you.

**Comment by vivek-bala** [comment]
No, not really. We do bulk submission of the tasks already. Hard to say without the profiles.

**Comment by andre-merzky** [comment]
I pushed some changes to the `fix/cheyenne` branch (in the `mpirun_dplace` launch method) which addresses core pinning for multithreaded tasks.  Can you give this a try, please?

**Comment by mturilli** [comment]
Blocked by #88
