### ISSUE TITLE
Annual Project Report

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#96]
Work on common sections and on site specific components

**Comment by shantenujha** [comment]
Please find a link to NSF Report for PY3:
https://docs.google.com/document/d/1uk_QuwuYY10CAB6x2bLpDiKbUmfGchOZKy5B-4EguEs/edit

I've updated most entries (where needed). PSU / Princeton / Rutgers team members should be able to update where explicitly requested.

**Comment by cervone** [comment]
Our document has been submitted and approved

**Comment by mturilli** [comment]
Submitted and approved.
